# config.yaml
tech_ai_feeds:
  - https://venturebeat.com/category/ai/feed/
  - https://www.analyticsvidhya.com/blog/category/news/feed/
  - https://spectrum.ieee.org/rss/artificial-intelligence/fulltext

general_feeds:
  - https://rss.sciencedaily.com/top/science.xml
  - https://www.medicalnewstoday.com/rss
  - https://www.bbc.co.uk/news/science_and_environment/rss.xml
  - https://rss.dw.com/rdf/rss-en-sci
  - https://naukawpolsce.pl/rss.xml
  - https://www.pap.pl/rss/nauka
  - https://www.polskieradio.pl/rss/kat/10.xml

